<?php

namespace Database\Seeders;

use App\Models\VillaDesign;
use Illuminate\Database\Seeder;

class VillaDesignSeeder extends Seeder
{
    public function run(): void
    {
        $samples = [
            [
                'slug' => 'saudi-majlis-partition',
                'type' => 'fitting',
                'title_en' => 'The Royal Majlis Privacy Partition',
                'title_ar' => 'فاصل الخصوصية للمجلس الملكي والمشربية العصرية',
                'tagline' => 'Warm champagne gold anodized aluminum with 10mm vertical fluted ribbed privacy glass and acoustic hermetic seal.',
                'category_key' => 'privacy_partition',
                'category_name_en' => 'Privacy & Mashrabiya',
                'category_name_ar' => 'فواصل الخصوصية والمشربية',
                'location_tag' => 'Riyadh Villa · Hittin District',
                'photo_url' => 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
                'detail_photo_url' => 'https://images.unsplash.com/photo-1541123437800-1bb1317badc2?auto=format&fit=crop&w=1200&q=80',
                'price_usd' => 2840,
                'price_sar' => 10650,
                'advance_deposit_usd' => 1136,
                'advance_deposit_sar' => 4260,
                'features' => [
                    'Visual Privacy between Men’s Majlis & Dining Area',
                    'Acoustic Sound Dampening (38dB noise barrier)',
                    'Champagne Gold Electro-Sealed Anodization',
                ],
                'specs' => [
                    'dimensions' => '96"H × 72"W (2.44m × 1.83m)',
                    'finishOrFabric' => 'Champagne Gold Anodized (6063-T6 Structural Alloy)',
                    'coreMaterial' => '10mm Fluted Ribbed Safety Glass',
                    'hardware' => '3×2 Architectural Grid Mullions + Hydraulic Soft-Close Pivot',
                ],
                'config_data' => [
                    'finishId' => 'champagne_gold',
                    'glassId' => 'fluted_ribbed',
                    'heightInches' => 96,
                    'widthInches' => 72,
                    'gauge' => '2.0mm',
                    'mullionStyle' => 'grid_3x2',
                    'addons' => ['acoustic_seal' => true, 'hydraulic_damper' => true, 'thermal_barrier' => false],
                ],
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'slug' => 'saudi-majlis-sofa-royal',
                'type' => 'sofa',
                'title_en' => 'The Diwaniya Grand Modular Salon',
                'title_ar' => 'طقم كنب المجلس والديوانية الملكية المعمارية',
                'tagline' => 'Reconfigurable luxury 4-piece salon with generous 42" deep lounge seating wrapped in cognac full-grain Tuscan saddle leather.',
                'category_key' => 'majlis',
                'category_name_en' => 'Royal Majlis & Salons',
                'category_name_ar' => 'المجالس وصالونات الاستقبال',
                'location_tag' => 'Riyadh Penthouse · Diplomatic Quarter',
                'photo_url' => 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1200&q=80',
                'detail_photo_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80',
                'price_usd' => 4850,
                'price_sar' => 18188,
                'advance_deposit_usd' => 1940,
                'advance_deposit_sar' => 7275,
                'features' => [
                    'Deep 42" Lounge Depth for Generous Saudi Hospitality',
                    'Full-Grain Leather that patinates richer with age',
                    'Solid Hardwood Frame rated for 15+ years of gatherings',
                ],
                'specs' => [
                    'dimensions' => '136"W × 42"D Lounge (3.45m Modular Width)',
                    'finishOrFabric' => 'Cognac Saddle Full-Grain Tuscan Leather',
                    'coreMaterial' => 'Multi-Density Resilience Core + Down-Feather Top Layer',
                    'hardware' => 'Matte Architectural Black Powder-Coated Steel Plinth',
                ],
                'config_data' => [
                    'layoutId' => 'grand_modular',
                    'fabricId' => 'cognac_leather',
                    'legId' => 'black',
                    'seatDepth' => 'deep_lounge',
                    'cushionCore' => 'down_blend',
                ],
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'slug' => 'saudi-thermal-window',
                'type' => 'fitting',
                'title_en' => 'Riyadh 50°C Thermal Break Window System',
                'title_ar' => 'نوافذ العزل الحراري الفائق لمناخ الرياض (مقاومة 50° مئوية)',
                'tagline' => 'Engineered with polyamide thermal barrier and double-glazed Low-E solar glass to block desert heat, UV radiation, and micro-sand.',
                'category_key' => 'thermal_window',
                'category_name_en' => '50°C Thermal Windows',
                'category_name_ar' => 'نوافذ العزل الحراري (مقاومة 50°م)',
                'location_tag' => 'Central KSA · Riyadh Desert Climate Approved',
                'photo_url' => 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
                'detail_photo_url' => 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
                'price_usd' => 2420,
                'price_sar' => 9075,
                'advance_deposit_usd' => 968,
                'advance_deposit_sar' => 3630,
                'features' => [
                    'SASO-compliant U-Value < 1.4 W/m²K for Desert Heat',
                    'Double EPDM Compression Gasket resists sandstorms',
                    'Low-E Solar Guard blocks 98% of solar UV glare',
                ],
                'specs' => [
                    'dimensions' => '84"H × 60"W (2.13m × 1.52m Casement)',
                    'finishOrFabric' => 'Matte Architectural Black (Zero-Glare UV Anodized)',
                    'coreMaterial' => 'Low-Iron Double-Glazed Argon Insulated Glass',
                    'hardware' => 'Integrated Thermal Break Strip + Concealed Multi-Point Locks',
                ],
                'config_data' => [
                    'finishId' => 'matte_black',
                    'glassId' => 'ultra_clear',
                    'heightInches' => 84,
                    'widthInches' => 60,
                    'gauge' => '2.0mm',
                    'mullionStyle' => 'minimal',
                    'addons' => ['acoustic_seal' => true, 'hydraulic_damper' => false, 'thermal_barrier' => true],
                ],
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'slug' => 'saudi-family-sofa',
                'type' => 'sofa',
                'title_en' => 'The Neom Alabaster Bouclé Sectional',
                'title_ar' => 'كنب صالة العائلة الفاخرة بقماش البوكليه العاجي',
                'tagline' => 'Sculptural organic silhouette wrapped in soft Italian bouclé with natural American walnut legs for serene family living.',
                'category_key' => 'family_living',
                'category_name_en' => 'Family Living Lounges',
                'category_name_ar' => 'صالات المعيشة العائلية',
                'location_tag' => 'Jeddah Coastal Villa · Al-Shati',
                'photo_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80',
                'detail_photo_url' => 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1200&q=80',
                'price_usd' => 2350,
                'price_sar' => 8812,
                'advance_deposit_usd' => 940,
                'advance_deposit_sar' => 3525,
                'features' => [
                    'Stain-Resistant Performance Treatment on Bouclé',
                    'Ultra-Plush Cloud Cushions with high resilience memory foam',
                    'Organic Rounded Form safe for children and modern aesthetics',
                ],
                'specs' => [
                    'dimensions' => '88"W × 42"D Deep Lounge Proportions',
                    'finishOrFabric' => 'Alabaster Textured Warm Cream Bouclé',
                    'coreMaterial' => 'Kiln-Dried Beech Hardwood + Down-Feather Blend',
                    'hardware' => 'Honed Solid American Walnut Plinth Legs',
                ],
                'config_data' => [
                    'layoutId' => 'linear_3_seat',
                    'fabricId' => 'cream_boucle',
                    'legId' => 'walnut',
                    'seatDepth' => 'deep_lounge',
                    'cushionCore' => 'down_blend',
                ],
                'sort_order' => 4,
                'is_active' => true,
            ],
            [
                'slug' => 'saudi-courtyard-screen',
                'type' => 'fitting',
                'title_en' => 'The Al-Khobar Smoked Bronze Solarium',
                'title_ar' => 'واجهة وفواصل الزجاج البرونزي المظلل للقصور',
                'tagline' => 'Statuary hand-brushed bronze frame with acoustic smoked bronze glass providing intimate glare-free outdoor courtyard views.',
                'category_key' => 'privacy_partition',
                'category_name_en' => 'Privacy & Mashrabiya',
                'category_name_ar' => 'فواصل الخصوصية والمشربية',
                'location_tag' => 'Eastern Province · Al-Khobar Villa',
                'photo_url' => 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=80',
                'detail_photo_url' => 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1200&q=80',
                'price_usd' => 3420,
                'price_sar' => 12825,
                'advance_deposit_usd' => 1368,
                'advance_deposit_sar' => 5130,
                'features' => [
                    'Smoked Bronze Tint cuts midday solar desert glare by 65%',
                    'Heavy 2.5mm Gauge Structural Aluminum Frame',
                    'Acoustic Lamination eliminates exterior street & wind noise',
                ],
                'specs' => [
                    'dimensions' => '108"H × 84"W (2.74m × 2.13m Double Height)',
                    'finishOrFabric' => 'Brushed Statuary Bronze Patinated Alloy',
                    'coreMaterial' => 'Smoked Bronze Acoustic Laminated Glass',
                    'hardware' => 'Floor-Anchored Stainless Pivot Hardware + EPDM Seals',
                ],
                'config_data' => [
                    'finishId' => 'brushed_bronze',
                    'glassId' => 'smoked_bronze',
                    'heightInches' => 108,
                    'widthInches' => 84,
                    'gauge' => '2.5mm',
                    'mullionStyle' => 'minimal',
                    'addons' => ['acoustic_seal' => true, 'hydraulic_damper' => true, 'thermal_barrier' => true],
                ],
                'sort_order' => 5,
                'is_active' => true,
            ],
            [
                'slug' => 'saudi-crescent-velvet',
                'type' => 'sofa',
                'title_en' => 'The Royal Emerald Crescent Salon',
                'title_ar' => 'طقم كنب الصالون الملكي باللون الزمردي المخملي',
                'tagline' => 'Curved crescent geometry upholstered in rich forest emerald velvet on brushed champagne brass stiletto legs.',
                'category_key' => 'majlis',
                'category_name_en' => 'Royal Majlis & Salons',
                'category_name_ar' => 'المجالس وصالونات الاستقبال',
                'location_tag' => 'Riyadh · Al-Nakheel Luxury Villa',
                'photo_url' => 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?auto=format&fit=crop&w=1200&q=80',
                'detail_photo_url' => 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1200&q=80',
                'price_usd' => 2980,
                'price_sar' => 11175,
                'advance_deposit_usd' => 1192,
                'advance_deposit_sar' => 4470,
                'features' => [
                    'Royal Emerald Velvet matching luxury Saudi reception aesthetics',
                    'Serpentine Arc encouraging conversational hospitality',
                    'Brushed Champagne Brass Base with scratch-proof floor protectors',
                ],
                'specs' => [
                    'dimensions' => '96"W × 38"D Sculptural Crescent (2.44m Arc)',
                    'finishOrFabric' => 'Low-Pile Forest Emerald Architectural Velvet',
                    'coreMaterial' => 'High-Density Ergonomic Curve Form + Pocket Springs',
                    'hardware' => 'Brushed Champagne Brass Stiletto Legs',
                ],
                'config_data' => [
                    'layoutId' => 'curved_crescent',
                    'fabricId' => 'emerald_velvet',
                    'legId' => 'brass',
                    'seatDepth' => 'standard',
                    'cushionCore' => 'cloud_plush',
                ],
                'sort_order' => 6,
                'is_active' => true,
            ],
        ];

        foreach ($samples as $sample) {
            VillaDesign::updateOrCreate(
                ['slug' => $sample['slug']],
                $sample
            );
        }
    }
}
